apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mqt4n-argo-application
  namespace: argocd-mqt4n
spec:
  destination:
    namespace: myapp-mqt4n
    server: https://kubernetes.default.svc
  source:
    path: dev
    repoURL: https://github.com/mqt4n/argocd-app.git
    targetRevision: HEAD
  sources: []
  project: argocd-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
